# -*- coding: utf-8 -*-
"""Box_Drawing_Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYajCmj_XrluP_HIOwyhoU82itzIQJu9
"""

def print_in_boxes(nums):
    topLeft = chr(0x2554)
    topRight = chr(0x2557)
    bottomLeft = chr(0x255A)
    bottomRight = chr(0x255D)
    horizontal = chr(0x2550)
    vertical = chr(0x2551)

    widths = [len(str(num)) + 2 for num in nums]
    for width in widths:
        print(topLeft + horizontal * width + topRight, end=" ")
    print()

    for i, num in enumerate(nums):
        num_str = f" {num} "
        print(vertical + num_str + vertical, end=" ")
    print()

    for width in widths:
        print(bottomLeft + horizontal * width + bottomRight, end=" ")
    print()

user_input = input("Enter numbers separated by spaces: ")

nums = list(map(int, user_input.split()))

print_in_boxes(nums)